services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    privileged: true
    shm_size: '8gb'
    volumes:
      - ../:/kaggle
    environment:
      - AWS_S3_BUCKET=user-dataset
      - MOUNT_POINT=/kaggle/s3storage
      - AWS_ACCESS_KEY=${your_access_key}
      - AWS_SECRET_ACCESS_KEY=${your_secret_access_key}
      - AWS_DEFAULT_REGION=${your_default_region}
    working_dir: /kaggle
    ports:
      - "8888:8888"
    tty: true
 